# Generated by Django 3.0.8 on 2021-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210223_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='node',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
