# Generated by Django 3.0.8 on 2021-05-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='node',
            new_name='note',
        ),
    ]
